Revert "enable-sigalitstack-everywhere.diff (#805826)"
This reverts commit abc4d6b07cdfcc22fc98a85a1222f10f4909c708.

Does not compile for unicore32-linux-user:

linux-user/syscall.c:8295:78: warning: dereferencing 'void *' pointer
       ret = do_sigaltstack(arg1, arg2, get_sp_from_cpustate((CPUArchState *)cpu_env));
  linux-user/syscall.c:8295:78: error: request for member 'regs' in something not a structure or union